### ISSUE TITLE
What CPUs are supported?

### ISSUE THREAD

**Issue by amanusk** [tiziw/iuvolt#6]
Could you tell me which Intel generations is this applicable to?

**Comment by tiziw** [comment]
As far as I know, since the method used to undervolt is reverse-engineered from ThrottleStop it should support any CPU ThrottleStop supports. What I've seen in the notebookreview forums is that it supports pretty much all generations of i-core series and I also saw people with Core 2 Duo undervolting their CPUs. 

I suggest you look through the notebookreview thread for more info on what CPUs others have undervolted with successfully.

**Comment by amanusk** [comment]
@tiziw, thanks for the tool. Works great on skylake. From what I have seen, only  Haswell or newer CPUSs can be undervolted if they are not K/X sku.
